controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

hello:
    path: /hello
    controller: App\Controller\TestController::hello
